version: "3.4"

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.19.9
    restart: on-failure:0
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./test-data"
      ENABLE_MODULES: text2vec-openai,generative-openai
      CLUSTER_HOSTNAME: "node1"

  corpus-query:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "8000:8000"

    environment:
      VECTOR_DB_URL: "http://weaviate:8080"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - weaviate
